server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gleysongomes/config-server-ms-repo.git
          default-label: main

app:
  service-registry:
    username: sr
    password: '12345'
  config-server:
    username: cs
    password: '12345'

eureka:
  client:
    service-url:
      defaultZone: 'http://${app.service-registry.username}:${app.service-registry.password}@localhost:8761/eureka'
  instance:
    hostname: localhost

